### PR TITLE
Dev flights

### PR DESCRIPTION
**Pull request by veitu**

### CODE REVIEW

**Review by han16nah — CHANGES_REQUESTED** [review]
Looks good, can you update the tests which are now failing with the updated emission factors? see [here](https://github.com/pledge4future/co2calculator/actions/runs/3847389377/jobs/6553789032)
Thanks a lot!

**Comment by han16nah** [comment]
Awesome! :)

**Review by han16nah — APPROVED** [review]

**Comment by han16nah** [comment]
can be merged right?

**Comment by veitu** [comment]
oh yes it can

han16nah ***@***.***> schrieb am So., 26. Feb. 2023, 21:55:

**Pull request merged**
