### PR TITLE
Automate documentation update and hosting

### LINKED ISSUE #140: Host package documentation via GitHub Pages
As we have an already existing Sphinx documentation, we should consider hosting this documentation via GitHub pages. Currently, we have a link in our readme to the Pledge4Future WebApp, which is not optimal. I think it would be more efficient for users of the package if we host a technical documentation instead of a finished application that just uses the calculator package. 

I recommend the following steps: 

- [ ] Automize creation of documentation (this is related to #49)
- [ ] Create pipeline step that hosts sphinx docu to GitHub pages (like here: https://coderefinery.github.io/documentation/gh_workflow/)

### PR DESCRIPTION
**Pull request by codingfabi**
I created a workflow to host the existing sphinx docu via GitHub pages. Check out the hosted version here: https://pledge4future.github.io/co2calculator/
Documentation should get updated automatically with every commit to the main branch. 

Closes #140

### CODE REVIEW

**Review by veitu — APPROVED** [review]
Nice! I actually don't understand how the documentation is generated. Like how would I make changes, can I edit the rst files? For example, there is a small error in "Electricity" where it should say electricity instead of heating.

**Comment by han16nah** [comment]
Thanks @codingfabi, very cool!

@veitu Exactly! For this case, you would edit https://github.com/pledge4future/co2calculator/blob/main/docs/calculate/heating_electricity.rst accordingly. If needed, you can check out the [sphinx documentation on reStructuredText (rst)](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)

**Review by han16nah — DISMISSED** [review]

**Comment by codingfabi** [comment]
@veitu The idea would be that sphinx generates the documentation automatically from the docstrings you write for the functions, like [so](https://www.sphinx-doc.org/en/master/tutorial/automatic-doc-generation.html). This needs to be done in another task but we can have a quick chat about it sometime soon :)

**Comment by han16nah** [comment]
@codingfabi Hm, I just now noticed that this is not working yet.
We already use `.. autofunction::` and in my local build, it automatically shows the functions and their docstrings.. But on GitHub pages, it is just empty.
Here is the reason: 
grafik

I think in line 13 or the yml workflow file, we also need to install pandas. Let's see if it works then.

**Comment by codingfabi** [comment]
Would probably be the best option to just install all packages from the requirements.txt... I'll have a look

**Review by han16nah — APPROVED** [review]
Great!

**Pull request merged**
